import "../styles/globals.css";
import type { AppProps } from "next/app";
import * as React from "react";
import { QueryClientProvider, QueryClient } from "react-query";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = React.useState(() => new QueryClient());

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Lena&apos;s Unsplash App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />;
    </QueryClientProvider>
  );
}

export default MyApp;
